apiVersion: v1
kind: ConfigMap
metadata:
  name: logits-customizations
  namespace: {{ .Release.Namespace }}
data:
  labels: |-
    {{ .Values.labels | default (dict) | toJson }}
  annotations: |-
    {{ .Values.annotations | default (dict) | toJson }}
  tolerations: |-
    {{ .Values.tolerations | default (list) | toJson }}
  nodeSelector: |-
    {{ .Values.nodeSelector | default (dict) | toJson }}
