apiVersion: apps/v1
kind: Deployment
metadata:
  name: logits-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    logits.ai/component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      logits.ai/component: gateway
  template:
    metadata:
      labels:
        logits.ai/component: gateway
        {{ with .Values.labels }}{{ toYaml . | nindent 8 }}{{ end }}
      annotations:
        {{ with .Values.annotations }}{{ toYaml . | nindent 8 }}{{ end }}
    spec:
      serviceAccountName: logits-gateway
      containers:
      - name: gateway
        image: ghcr.io/logitsai/gateway:{{ .Chart.AppVersion }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LOGITS_ENV_ID
          valueFrom:
            secretKeyRef:
              name: logits-environment
              key: envID
        - name: LOGITS_ENV_KEY
          valueFrom:
            secretKeyRef:
              name: logits-environment
              key: envKey
        ports:
        - name: proxy
          containerPort: 8080
        - name: metrics
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
        - name: customizations
          mountPath: /etc/logits/customizations
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: labels
            fieldRef:
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              fieldPath: metadata.annotations
      - name: customizations
        configMap:
          name: logits-customizations
          optional: true
      tolerations:
        {{ with .Values.tolerations }}{{ toYaml . | nindent 8 }}{{ end }}
      nodeSelector:
        {{ with .Values.nodeSelector }}{{ toYaml . | nindent 8 }}{{ end }}
