apiVersion: v1
kind: Service
metadata:
  name: logits-gateway
  labels:
    logits.ai/component: gateway
spec:
  ports:
    - name: proxy
      port: 8080
      targetPort: 8080
  selector:
    logits.ai/component: gateway
